First cut of the module
matrix-org/synapse-bind-sydent pull request #1
Opened 2022-03-21 17:26 UTC by babolivier

This work is happening in the context of the Tchap mainlining. In Tchap, when a user is registered (which always requires an email to be set), the email is automatically bound to a Sydent instance using the internal API (so that their email can be looked up immediately, and without having to go through additional manual validation).

This module implements this behaviour by using the `on_user_registration` account validity callback, as well as a module API method added in https://github.com/matrix-org/synapse/pull/12195.

The CI is expecting to fail since https://github.com/matrix-org/synapse/pull/12195 hasn't made it into mainline CI yet, but it's all passing locally.

2022-03-23 12:19 UTC, reivilibre approved these changes, later dismissed
Looks good to me, I assume you've tested it works, so the comment is really just a question about how it works (with perhaps a point that it might be nice to document it readily, as it seems not immediately obvious).

2022-03-23 12:19 UTC, reivilibre commented on README.md
> +      use_https: false
Curious if this would be better written as one option, `https?://example.com`, much like you would in a client configuration screen. My experience with other software is that it's frustrating to have HTTPS gated behind a separate flag. Maybe it makes sense for what you have in mind though, so your judgement here.

2022-03-23 12:19 UTC, reivilibre commented on synapse_bind_sydent/__init__.py
> +        threepids = await self._api.get_threepids_for_user(user_id)
I'm somewhat confused, would be grateful if you could explain.

On registration, I would have thought there are *no* threepids for the user?

What are the semantics of the 3pids returned here, versus the ones we're about to 'bind'. Is it that the 3pids are registered for password reset purposes only, but this module makes them usable for IS lookups automatically?

2022-03-23 12:26 UTC, babolivier commented on synapse_bind_sydent/__init__.py
> +        threepids = await self._api.get_threepids_for_user(user_id)
The idea is to retrieve the threepids the user signed up with (if any), though I've just realised the callback is called _before_ we actually store those in the db (I'll open a Synapse PR to move the callback to a more sensible place).

2022-03-23 12:28 UTC, babolivier commented on README.md
> +      use_https: false
The module needs the IS's hostname alone (ie without a protocol scheme) to store the association once it's been created. Though I could have the module extract that from the full base URL instead.

2022-03-25 18:48 UTC, babolivier commented
I've rewritten a bit of the module so it now uses the callback to https://github.com/matrix-org/synapse/pull/12302, and binds assocs when they're verified on the HS rather than only on registration.

2022-03-31 13:32 UTC, reivilibre requested changes
Looks fine otherwise, I think!

2022-03-31 13:32 UTC, reivilibre commented on synapse_bind_sydent/__init__.py
> +        self._sydent_host = config.sydent_base_url.replace(f"{scheme}://", "")
Curious why you'd go so far to parse the URL and then chuck that away and fall back to string replacement? :sweat_smile: 

Do you want the hostname (`https://sydent/` → `sydent`) or the hostname with port (`https://sydent:4242/` → `sydent:4242`) (this also includes username and password if specified, but meh...)?

```suggestion
        self._sydent_host = urlparse(config.sydent_base_url).hostname
```

or

```suggestion
        self._sydent_host = urlparse(config.sydent_base_url).netloc
```

2022-03-31 13:32 UTC, reivilibre commented on synapse_bind_sydent/__init__.py
> +        ].startswith("https://"):
```suggestion
        if urlparse(config["sydent_base_url"]).scheme not in ("http", "https"):
```

(This also lets you type `HTTPS://` if you really want to, not that it really matters)

2022-03-31 13:32 UTC, reivilibre commented on synapse_bind_sydent/__init__.py
> +        self._sydent_host = config.sydent_base_url.replace(f"{scheme}://", "")
Reading 
```
            id_server: The identity server the 3PID association has been registered on.
                This should only be the domain (or IP address, optionally with the port
                number) for the identity server. This will be used to reach out to the
                identity server using HTTPS (unless specified otherwise by Synapse's
                configuration) when attempting to unbind the third-party identifier.
```

I think you really don't want any potential path component to creep in. I think you want `netloc` in this case.

2022-04-05 09:12 UTC, reivilibre approved these changes
Seems to require reformatting, but AST-wise this is fine

Edit: actually it looks like `black` might be broken? Hrmph.

2022-04-05 10:57 UTC, merged